name: Auto-merge PRs

on:
  pull_request:
    types: [opened, reopened, ready_for_review, synchronize]

jobs:
  auto-merge:
    if: ${{ !github.event.pull_request.draft }}
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: actions/checkout@v6
      - run: gh pr merge --auto --merge ${{ github.event.number }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
